"""Lazy loader for artifacts/team_mapping.json (Phase B2).

The JSON is generated by bootstrap/team_mapping_bootstrap.py. Shape:

    {
        "version": 1,
        "mappings": {
            "<db_team_name>": {
                "api_id": int, "api_name": str,
                "league_id": int, "score": float, "reason": str
            }
        }
    }

We cache the parsed mappings in-process. A missing, unreadable, or
schema-broken file is treated as "no mapping available" — callers
get `{}` back and must fall back to their legacy name-based path.
USE_TEAM_MAPPING = "off" short-circuits loading entirely.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from src.config import USE_TEAM_MAPPING

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_MAPPING_PATH = _REPO_ROOT / "artifacts" / "team_mapping.json"

_cache: Optional[dict[str, dict]] = None
_load_attempted = False


def get_mapping() -> dict[str, dict]:
    """Return {db_team_name: {api_id, api_name, league_id, score, reason}}.

    Returns {} when USE_TEAM_MAPPING == "off", when the file is missing,
    or when the JSON is malformed. Logged once per process.
    """
    global _cache, _load_attempted

    if USE_TEAM_MAPPING == "off":
        return {}
    if _cache is not None:
        return _cache
    if _load_attempted:
        return {}

    _load_attempted = True
    if not _MAPPING_PATH.exists():
        logger.warning("[team_mapping] %s missing — falling back to name-only matching",
                       _MAPPING_PATH)
        _cache = {}
        return _cache

    try:
        payload = json.loads(_MAPPING_PATH.read_text(encoding="utf-8"))
        mappings = payload.get("mappings") or {}
        if not isinstance(mappings, dict) or not mappings:
            raise ValueError("no mappings key / empty")
    except Exception as e:
        logger.warning("[team_mapping] failed to parse %s: %s — fallback to name-only",
                       _MAPPING_PATH, e)
        _cache = {}
        return _cache

    logger.info("[team_mapping] loaded %d entries from %s (mode=%s)",
                len(mappings), _MAPPING_PATH, USE_TEAM_MAPPING)
    _cache = mappings
    return _cache


def lookup_api_id(db_team_name: str) -> Optional[int]:
    """Return api_id for a DB team name, or None if unmapped."""
    if not db_team_name:
        return None
    entry = get_mapping().get(db_team_name.strip())
    if not entry:
        return None
    return entry.get("api_id")


def reset_cache() -> None:
    """Test hook — clear the cache so the next get_mapping() re-reads the file."""
    global _cache, _load_attempted
    _cache = None
    _load_attempted = False
