"""Auto-generated từ scripts/discover_pinnacle_sports.py — KHÔNG sửa tay.

Chạy lại script trên VPS khi muốn refresh list giải Pinnacle cover.

Structure:
- LEAGUES_FULL: {code: human_title}     → merged vào src.config.LEAGUES
- ODDS_SPORTS_FULL: {code: sport_key}   → merged vào src.config.ODDS_SPORTS

Merge *không* ghi đè entry đã có — chỉ thêm giải chưa có.
"""

# (code) → (human-readable title)
LEAGUES_FULL = {
    "PRIMERA_DIVISION_ARGENTINA": "Primera División - Argentina",
    "A_LEAGUE": "A-League",
    "AUSTRIAN_FOOTBALL_BUNDESLIGA": "Austrian Football Bundesliga",
    "BELGIUM_FIRST_DIV": "Belgium First Div",
    "BRAZIL_SERIE_A": "Brazil Série A",
    "BRAZIL_SERIE_B": "Brazil Série B",
    "PRIMERA_DIVISION_CHILE": "Primera División - Chile",
    "SUPER_LEAGUE_CHINA": "Super League - China",
    "DENMARK_SUPERLIGA": "Denmark Superliga",
    "CHAMPIONSHIP": "Championship",
    "LEAGUE_1": "League 1",
    "LEAGUE_2": "League 2",
    "EPL": "EPL",
    "FA_CUP": "FA Cup",
    "FIFA_WORLD_CUP": "FIFA World Cup",
    "VEIKKAUSLIIGA_FINLAND": "Veikkausliiga - Finland",
    "COUPE_DE_FRANCE": "Coupe de France",
    "LIGUE_1_FRANCE": "Ligue 1 - France",
    "LIGUE_2_FRANCE": "Ligue 2 - France",
    "BUNDESLIGA_GERMANY": "Bundesliga - Germany",
    "BUNDESLIGA_2_GERMANY": "Bundesliga 2 - Germany",
    "3_LIGA_GERMANY": "3. Liga - Germany",
    "SUPER_LEAGUE_GREECE": "Super League - Greece",
    "COPPA_ITALIA": "Coppa Italia",
    "SERIE_A_ITALY": "Serie A - Italy",
    "SERIE_B_ITALY": "Serie B - Italy",
    "J_LEAGUE": "J League",
    "K_LEAGUE_1": "K League 1",
    "LEAGUE_OF_IRELAND": "League of Ireland",
    "LIGA_MX": "Liga MX",
    "DUTCH_EREDIVISIE": "Dutch Eredivisie",
    "ELITESERIEN_NORWAY": "Eliteserien - Norway",
    "EKSTRAKLASA_POLAND": "Ekstraklasa - Poland",
    "PRIMEIRA_LIGA_PORTUGAL": "Primeira Liga - Portugal",
    "PREMIER_LEAGUE_RUSSIA": "Premier League - Russia",
    "SAUDI_PRO_LEAGUE": "Saudi Pro League",
    "LA_LIGA_SPAIN": "La Liga - Spain",
    "LA_LIGA_2_SPAIN": "La Liga 2 - Spain",
    "PREMIERSHIP_SCOTLAND": "Premiership - Scotland",
    "ALLSVENSKAN_SWEDEN": "Allsvenskan - Sweden",
    "SUPERETTAN_SWEDEN": "Superettan - Sweden",
    "SWISS_SUPERLEAGUE": "Swiss Superleague",
    "TURKEY_SUPER_LEAGUE": "Turkey Super League",
    "UEFA_CHAMPIONS_LEAGUE": "UEFA Champions League",
    "UEFA_EUROPA_CONFERENCE_LEAGUE": "UEFA Europa Conference League",
    "UEFA_EUROPA_LEAGUE": "UEFA Europa League",
    "MLS": "MLS",
}

# (code) → (Odds API sport_key)
ODDS_SPORTS_FULL = {
    "PRIMERA_DIVISION_ARGENTINA": "soccer_argentina_primera_division",
    "A_LEAGUE": "soccer_australia_aleague",
    "AUSTRIAN_FOOTBALL_BUNDESLIGA": "soccer_austria_bundesliga",
    "BELGIUM_FIRST_DIV": "soccer_belgium_first_div",
    "BRAZIL_SERIE_A": "soccer_brazil_campeonato",
    "BRAZIL_SERIE_B": "soccer_brazil_serie_b",
    "PRIMERA_DIVISION_CHILE": "soccer_chile_campeonato",
    "SUPER_LEAGUE_CHINA": "soccer_china_superleague",
    "DENMARK_SUPERLIGA": "soccer_denmark_superliga",
    "CHAMPIONSHIP": "soccer_efl_champ",
    "LEAGUE_1": "soccer_england_league1",
    "LEAGUE_2": "soccer_england_league2",
    "EPL": "soccer_epl",
    "FA_CUP": "soccer_fa_cup",
    "FIFA_WORLD_CUP": "soccer_fifa_world_cup",
    "VEIKKAUSLIIGA_FINLAND": "soccer_finland_veikkausliiga",
    "COUPE_DE_FRANCE": "soccer_france_coupe_de_france",
    "LIGUE_1_FRANCE": "soccer_france_ligue_one",
    "LIGUE_2_FRANCE": "soccer_france_ligue_two",
    "BUNDESLIGA_GERMANY": "soccer_germany_bundesliga",
    "BUNDESLIGA_2_GERMANY": "soccer_germany_bundesliga2",
    "3_LIGA_GERMANY": "soccer_germany_liga3",
    "SUPER_LEAGUE_GREECE": "soccer_greece_super_league",
    "COPPA_ITALIA": "soccer_italy_coppa_italia",
    "SERIE_A_ITALY": "soccer_italy_serie_a",
    "SERIE_B_ITALY": "soccer_italy_serie_b",
    "J_LEAGUE": "soccer_japan_j_league",
    "K_LEAGUE_1": "soccer_korea_kleague1",
    "LEAGUE_OF_IRELAND": "soccer_league_of_ireland",
    "LIGA_MX": "soccer_mexico_ligamx",
    "DUTCH_EREDIVISIE": "soccer_netherlands_eredivisie",
    "ELITESERIEN_NORWAY": "soccer_norway_eliteserien",
    "EKSTRAKLASA_POLAND": "soccer_poland_ekstraklasa",
    "PRIMEIRA_LIGA_PORTUGAL": "soccer_portugal_primeira_liga",
    "PREMIER_LEAGUE_RUSSIA": "soccer_russia_premier_league",
    "SAUDI_PRO_LEAGUE": "soccer_saudi_arabia_pro_league",
    "LA_LIGA_SPAIN": "soccer_spain_la_liga",
    "LA_LIGA_2_SPAIN": "soccer_spain_segunda_division",
    "PREMIERSHIP_SCOTLAND": "soccer_spl",
    "ALLSVENSKAN_SWEDEN": "soccer_sweden_allsvenskan",
    "SUPERETTAN_SWEDEN": "soccer_sweden_superettan",
    "SWISS_SUPERLEAGUE": "soccer_switzerland_superleague",
    "TURKEY_SUPER_LEAGUE": "soccer_turkey_super_league",
    "UEFA_CHAMPIONS_LEAGUE": "soccer_uefa_champs_league",
    "UEFA_EUROPA_CONFERENCE_LEAGUE": "soccer_uefa_europa_conference_league",
    "UEFA_EUROPA_LEAGUE": "soccer_uefa_europa_league",
    "MLS": "soccer_usa_mls",
}
